name: Generate IPTV

on:
  push:
    branches:
      - main   # 每次 push 主分支时触发
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0 点自动运行一次

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run IPTV script
      run: python hebing.py

    - name: Commit and push
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"
        git add IPTV.txt
        git commit -m "自动更新 IPTV.txt" || echo "No changes to commit"
        git push
